Update github action to verify qlpack version and auto-publish package (#128)
* update github action

* remove jobs from action for faster testing

* github action job updates

* github action job updates

* github action job updates

* test change of qls file without changing qlpack version

* bug fix

* test change of qls file without changing qlpack version

* test empty commit after fail of qlpack version test

* test update of qlpack version

* test update of qlpack and qls

* test gh action

* fix action file

* fix action file

* update github action

* test change of qls file without changing qlpack version

* test github action

* test github action

* test github action

* test github action

* test github action

* test github action

* update qls

* test

* test github action

* test github action

* test github action

* test github action

* test github action

* update qlpack. should pass test

* update qlpack but not version. should fail test

* update qls and update qlpack but not version. should fail test

* update qlpack version but decrement version. should fail test

* update qlpack version and add publish job to workflow file

* back to just one job

* bug fix

* bug fix

* bug fix

* bug fix

* bug fix

* add publish

* fix publish

* bug fix

* bug fix

* add token

* uncomment and change back version

* comment for testing

* increment version

* add permissions to workflow file

* uncomment and change back version

* Update build-codeql.yaml to remove extra trigger branch 

Signed-off-by: Jacob Ronstadt <147542405+jacob-ronstadt@users.noreply.github.com>

* Update windows_mustfix_partial.qls back to original

Signed-off-by: Jacob Ronstadt <147542405+jacob-ronstadt@users.noreply.github.com>

* Update windows_recommended_partial.qls back to original

Signed-off-by: Jacob Ronstadt <147542405+jacob-ronstadt@users.noreply.github.com>

---------

Signed-off-by: Jacob Ronstadt <147542405+jacob-ronstadt@users.noreply.github.com>

diff --git a/.github/workflows/build-codeql.yaml b/.github/workflows/build-codeql.yaml
--- a/.github/workflows/build-codeql.yaml
+++ b/.github/workflows/build-codeql.yaml
@@ -1,7 +1,7 @@
 # Continuous integration action for the CodeQL components of this repo.
 # This downloads the CodeQL CLI and then builds all the queries in the "windows-drivers" folder.
 
-name: Build Windows CodeQL queries
+name: Build and Publish Windows CodeQL queries
 
 on:
   # Triggers the workflow on push or pull request events but only for the main and development branches
@@ -14,9 +14,11 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
+  build-publish:
     runs-on: windows-latest
-
+    permissions:
+      contents: read
+      packages: write
     steps:
     - name: Enable long git paths
       shell: cmd
@@ -26,7 +28,8 @@ jobs:
       uses: actions/checkout@v2
       with:
         path: .
-        
+        fetch-depth: 0
+
     - name: Download CodeQL CLI
       uses: i3h/download-release-asset@v1.2.0
       with:
@@ -66,6 +69,7 @@ jobs:
  
     - name: Run test script
       shell: pwsh
+      continue-on-error: true # Allow script to return non-zero exit code
       env:
         CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
         ACCOUNT_KEY: ${{ secrets.ACCOUNT_KEY }}
@@ -91,4 +95,39 @@ jobs:
       shell: cmd
       run: .\codeql-cli\codeql.cmd query compile --check-only .\src
 
-   
+    - name: Check for changes to qlpack
+      shell: pwsh
+      run: 
+        $qlpack_diff = git diff HEAD~1:src/qlpack.yml src/qlpack.yml;
+        $rec_diff = git diff HEAD~1:src/windows-driver-suites/windows_recommended_partial.qls src/windows-driver-suites/windows_recommended_partial.qls;
+        $mf_diff = git diff HEAD~1:src/windows-driver-suites/windows_mustfix_partial.qls src/windows-driver-suites/windows_mustfix_partial.qls;
+        if (!$qlpack_diff -and ($rec_diff -or $mf_diff)) { "Query suite file updated without updating qlpack version"; exit 1 }
+
+        $last_qlpack_commit = git log -n 1 --pretty=format:%H -- src/qlpack.yml;
+        $qlpack_changes =git show $last_qlpack_commit -- .\src\qlpack.yml;
+      
+        $last_mf_commit = git log -n 1 --pretty=format:%H -- src/windows-driver-suites/windows_mustfix_partial.qls;
+        $last_rec_commit = git log -n 1 --pretty=format:%H -- src/windows-driver-suites/windows_recommended_partial.qls;
+        $commits_since_qlpack_change = [int](git rev-list --count HEAD...$last_qlpack_commit);
+        $commits_since_mf_change = [int](git rev-list --count HEAD...$last_mf_commit);
+        $commits_since_rec_change = [int](git rev-list --count HEAD...$last_rec_commit);
+
+        if ($commits_since_qlpack_change -gt $commits_since_mf_change) { "Mustfix query suite file modified without updating version"; exit 1 }; 
+        if ($commits_since_qlpack_change -gt $commits_since_rec_change) {"Recommended query suite file modified without updating version"; exit 1 };
+
+        try{$old_qlpack_version = [version]($qlpack_changes -match "-version").Substring(10);} catch {"Changed qlpack.yml without updating version"; exit 1 }
+        try{$new_qlpack_version = [version]($qlpack_changes -match "\+version").Substring(10);} catch {"Changed qlpack.yml without updating version"; exit 1 }
+        if ($new_qlpack_version -gt $old_qlpack_version) { exit 0 } else { "qlpack.yml version not incremented"; exit 1 }
+
+    - name: Publish New CodeQL Pack
+      shell: pwsh
+      env:
+        GITHUB_TOKEN:  ${{ secrets.GITHUB_TOKEN }}
+
+      run: 
+        $build = git rev-parse --short HEAD;
+        $version =( Select-String .\src\qlpack.yml -Pattern "version").line;
+        $new_ver = "$version-alpha+$build";
+        (Get-Content .\src\qlpack.yml).Replace($version, $new_ver) | Set-Content .\src\qlpack.yml;
+        .\codeql-cli\codeql.cmd pack publish --allow-prerelease ./src;
+    
